import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import TransitionProvider from "@/providers/TransitionProvider";
import SmoothScroll from "@/components/SmoothScroll";
import ThemeProvider from "@/providers/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="opacity-0">
        {" "}
        <Navbar />
        <div className="overflow-hidden red:bg-[#ede4dd] red:text-[#ff0001] dark:bg-[#000]  dark:text-white blue:text-[#0040ff] blue:bg-[#ffffff]">
          {" "}
          <ThemeProvider>
            <TransitionProvider>
              <main id="transition-target">
                <SmoothScroll>{children}</SmoothScroll>
              </main>
            </TransitionProvider>
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
